# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ba19e9b38ae313fe0309644adeba2a4422e038d5e7f2e224a1f33f9a47c7d64955327c0c5b8ab1eaa56fcbff027637dfba321e623a9edab0af46d7b1448c3d0c

test:
  secret_key_base: 3e651512c0ed24bc8ffa3fb29cf2217d216e71ebac99dbcf025bda046b11f2ae9586fb3fd71a10d34844ff4425e2ffe6ffd4424f512efe9667f81e07fde310d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
